import { Router } from "express";
import { requireAuth } from "../../middleware/requireAuth.js";
import { catchAsync } from "../../utils/catchAsync.js";
import { getNotifications, markAllNotificationsRead, markNotificationRead } from "./notification.controller.js";
const router: Router = Router();
router.get("/", requireAuth, catchAsync(getNotifications));
router.patch("/read-all", requireAuth, catchAsync(markAllNotificationsRead));
router.patch("/:notificationId/read", requireAuth, catchAsync(markNotificationRead));
export const NotificationRoutes = router;
export default router;
